"""Initial migrationdd.

Revision ID: 4cb629590da5
Revises: 573e36a1c5d0
Create Date: 2025-04-04 20:54:01.894447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb629590da5'
down_revision = '573e36a1c5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('join_date')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
